name: PHP Coding Style Fixer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcsfixer-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    
    - name: Install PHP CS Fixer
      run: composer global require friendsofphp/php-cs-fixer
    
    - name: Check PHP code style
      run: ~/vendor/composer/bin/php-cs-fixer fix -vvv --show-progress=dots
